### ISSUE TITLE
Matlab

### ISSUE THREAD

**Issue by MRphysics4life** [kmcgregor123456/CVNRimagingCore#10]
Hi,
Matlab needs a license update on Pano
Matlab needs to be installed on Rama
All other systems (qball 1-4, lens, and ralph) were checked, and have Matlab working.
Best,
LCK

**Comment by kmcgregor123456** [comment]
Working on this now.

**Comment by kmcgregor123456** [comment]
Matlab updated on pano. INstalling on rama
