### ISSUE TITLE
Can't use VMware to remote connect

### ISSUE THREAD

**Issue by simonero** [kmcgregor123456/CVNRimagingCore#18]
Can't connect to internet on VMWare and thus can't download/install/use X2Go or troubleshoot, or work remotely on most things.

**Comment by simonero** [comment]
I am currently at the VA and have my VMWare ready to troubleshoot in case you are in the building today.  Thank you.

**Comment by kmcgregor123456** [comment]
bring me the VMware when you can

**Comment by kmcgregor123456** [comment]
I have updated the VMware image. This includes modernization of almost all major software in the image. The new revision will be known as Xubuntu_05172018

**Comment by simonero** [comment]
Can you please send me a link to the disk image, and can we please set a specific time to meet.  I went to the WMB Tuesday afternoon to meet with you and you were no longer there.  If I can get it working prior with the updated image and don't need to meet I'll let you know.  I'm available at the WMB until 2pm tomorrow, and theoretically could meet at the VA earlier depending on amble time to commute to the WMB.

**Comment by kmcgregor123456** [comment]
I have the new image running on monoamine and will upload the link shortly.


================
Keith M. McGregor, PhD
VA RR&D Atlanta CVNR
Emory University, Department of Neurology
352.359.8084
www.varrd.emory.edu<http://www.varrd.emory.edu>

________________________________

**Comment by simonero** [comment]
Reminder to post link so I can follow up and report back regarding resolution of issues.

**Comment by simonero** [comment]
Issue not resolved - unable to attain network connectivity on VMWare.  Closing issue because troubleshooting has been done and no further actions are being taken at this time.  If a solutions arises in the future, I will amend or post something to document the solution.
