### ISSUE TITLE
permission issues: GABA-L

### ISSUE THREAD

**Issue by MRphysics4life** [kmcgregor123456/CVNRimagingCore#22]
Due to issues with spatnorm and restarting analysis of rsfMRI, I am cleaning up files. To organize, I need permissions to move some files or folders (created by users that have exited the lab):

/data/qb/Atlanta/Crosson_GABA-L/S2105/preprocfiles/MPRAGE/S2105_MPRAGE_dcm2nii.nii.gz

/data/qb/Atlanta/Crosson_GABA-L/S1107/preprocfiles/MPRAGE/segfiles/
/data/qb/Atlanta/Crosson_GABA-L/S1110/preprocfiles/MPRAGE/segfiles/
/data/qb/Atlanta/Crosson_GABA-L/S2005/preprocfiles/MPRAGE/segfiles/
/data/qb/Atlanta/Crosson_GABA-L/S2007/preprocfiles/MPRAGE/segfiles/
/data/qb/Atlanta/Crosson_GABA-L/S2008/preprocfiles/MPRAGE/segfiles/
/data/qb/Atlanta/Crosson_GABA-L/S2011/preprocfiles/MPRAGE/segfiles/
/data/qb/Atlanta/Crosson_GABA-L/S2012/preprocfiles/MPRAGE/segfiles/
/data/qb/Atlanta/Crosson_GABA-L/S2110/preprocfiles/MPRAGE/segfiles/
/data/qb/Atlanta/Crosson_GABA-L/S2113/preprocfiles/MPRAGE/segfiles/
/data/qb/Atlanta/Crosson_GABA-L/S2114/preprocfiles/MPRAGE/segfiles/

**Comment by kmcgregor123456** [comment]
changing permissions now. should be complete in 12 minutes

**Comment by MRphysics4life** [comment]
Great! Thank you!



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by kmcgregor123456** [comment]
complete

**Comment by MRphysics4life** [comment]
Perfect! Everything could be manipulated as I needed it to be. Thank you!!!!
