### ISSUE TITLE
matlab license

### ISSUE THREAD

**Issue by GiriKrish** [kmcgregor123456/CVNRimagingCore#25]
Matlab license on qball4 is not updated. Not sure about the other clusters (qball 1, 2, 3, ralph, lens etc)

**Comment by kmcgregor123456** [comment]
matlab licence reports up to date on qball4 . can you send screenshot of error?

**Comment by GiriKrish** [comment]
This was the feedback I got from Stella when we were discussing yesterday. I can confirm with her later this afternoon.

**Comment by smtran** [comment]
I don't remember what the error was exactly, but when trying to run FIX on qball4, there was an error after the feature extraction step mentioning matlab. I can see if this error is reproduced and send you a screen shot.

**Comment by kmcgregor123456** [comment]
That's a different error. 

The proper path for the training files should be: /usr/local/fix1.06/training_files

This should repair the issue.

**Comment by kmcgregor123456** [comment]
so the command line should read:

For example: 

/usr/local/fix1.06/fix -c <icadirectory.ica> /usr/local/fix1.06/training_files/Standard.R 15

**Comment by kmcgregor123456** [comment]
tested. works.
