### ISSUE TITLE
Melodic not opening

### ISSUE THREAD

**Issue by GiriKrish** [kmcgregor123456/CVNRimagingCore#26]
Melodic GUI failed to open on qball 1. Sounds like some environment setting issue within FSL.

**Comment by kmcgregor123456** [comment]
Please provide more information from command line error

**Comment by GiriKrish** [comment]
That’s a question for Anna because when I sat with her yesterday she showed me the problem. I can chat with her and ask her to send the error.

**Comment by kmcgregor123456** [comment]
error fixed with FSLDIR addition
