### ISSUE TITLE
LINDA on Lens

### ISSUE THREAD

**Issue by MRphysics4life** [kmcgregor123456/CVNRimagingCore#3]
![20180330_134022](https://user-images.githubusercontent.com/18470472/38315186-edafc864-37f5-11e8-9809-054c27a48d82.jpg)
Hi,
LINDA on Lens is encountering a problem in one of its 'which' loops (see attached blurry picture). Currently the Ralph version is working fine, so this is not high priority. However, as we collect more stroke data, we may encounter a computational resource issue if we only have LINDA installed on one node. 
Best,
LCK

**Comment by kmcgregor123456** [comment]
working on it.

**Comment by kmcgregor123456** [comment]
perhaps...steady cam?

**Comment by kmcgregor123456** [comment]
updated linda to version 0.2.7 from 0.2.6 on lens running a test subject now:
/data/qb/Atlanta/Krishnamurthy_UE_stroke_2009/s201/ses1/preprocfiles/MPRAGE/S201_MPRAGE.nii.gz

It appears to be working:

randomForest 4.6-14
Type rfNews() to see new features/changes/bug fixes.
Enter file name: /data/qb/Atlanta/Krishnamurthy_UE_stroke_2009/s201/ses1/preprocfiles/MPRAGE/s201_MPRAGE.nii.gz
10:25 Loading file: s201_MPRAGE.nii.gz 
10:25 Creating folder: /data/qb/Atlanta/Krishnamurthy_UE_stroke_2009/s201/ses1/preprocfiles/MPRAGE/linda 
10:25 Loading template... 
10:25 Skull stripping... (long process) 
10:38 Saving skull stripped files 
10:38 Loading LINDA model 
10:38 Computing asymmetry mask... 
10:39 Saving asymmetry mask... 
10:39 Running 1st registration... 
10:41 Feature calculation... 
10:43 Running 1st prediction... 
10:44 Saving 1st prediction... 
10:44 Backprojecting 1st prediction... 
10:44 Running 2nd registration... 
10:46 Feature calculation... 
10:48 Running 2nd prediction... 
10:49 Saving 2nd prediction... 
10:49 Backprojecting 2nd prediction... 
10:49 Running 3rd registration... (long process)

**Comment by kmcgregor123456** [comment]
Linda successfully runs on lens now
