### ISSUE TITLE
Increased Image processing access to new and existing users

### ISSUE THREAD

**Issue by GiriKrish** [kmcgregor123456/CVNRimagingCore#30]
In the last several months we have seen a steady increase in number of users (such as Rachael, Lawson, Anna, Kyle, Mehdi, Aarushi, and hopefully many more) of neuroimaging lab. Specifically when they are physically at the VA,  I think it will good to have more accessible computers (that supports image analysis) and space in the Neuroimaging lab for our users. Currently, we only have Tasaki on which a lot of users don't have account, and the other mac which has malfunctioning display. I also think it is not reasonable to expect every user of Neuroimaging lab to bring their own laptop to do lab work, and in the process if their personal laptop fails/breaks then they are stuck with days of not having convenient means (and help with fixing any job-related computer issues) to do their job.

I believe this concern will also need Bruce's advice and inputs. I am just putting it out there ...

**Comment by kmcgregor123456** [comment]
I will bring this up with Dr. Crosson. Funds are limited, however, so we may have to be creative.

**Comment by kmcgregor123456** [comment]
I have swapped out the problematic Mac in the imaging Lab with a more modern one. There will be a common user to be specified on a non-public location.

**Comment by kmcgregor123456** [comment]
Please provide specific problems or errors for this forum.
