### ISSUE TITLE
updated spm to support GIFT tools

### ISSUE THREAD

**Issue by GiriKrish** [kmcgregor123456/CVNRimagingCore#31]
We will need updated spm (on all clusters) to support GIFT analysis. Stella will be an immediate user, and potentially Anna.

**Comment by smtran** [comment]
On a related note, we will also need GIFT on at least one of the computers. Thank you!
http://mialab.mrn.org/software/

**Comment by kmcgregor123456** [comment]
We have to be VERY careful with GIFT. GIFT requires matlab runtime of R2016a to work. However, FIX requires matlab runtime R2014a to function. It may cause problems to install the two runtime compilers on the same machine. I propose we do a test machine at this point.

**Comment by kmcgregor123456** [comment]
spm12 has been installed on all of the machines. GIFT is also available as matlab scripts.

Note: to launch SPM, you have to type:
addpath /usr/local/spm12
then type: spm

**Comment by kmcgregor123456** [comment]
GIFT is known as GroupICATv4.0b
