### ISSUE TITLE
lens 'which fix'

### ISSUE THREAD

**Issue by MRphysics4life** [kmcgregor123456/CVNRimagingCore#36]
On lens: 'which fix' reports the fix path as /opt/fix/fix, even though updated fix path is usr/local/fix1.066/fix
Need to delete previous fix install?

**Comment by kmcgregor123456** [comment]
yes, I will delete the older FIX


================
Keith M. McGregor, PhD
VA RR&D Atlanta CVNR
Emory University, Department of Neurology
352.359.8084
www.varrd.emory.edu<http://www.varrd.emory.edu>

________________________________

**Comment by kmcgregor123456** [comment]
I removed the older fix. The proper path is:

/usr/local/fix1.06

I have updated all of the machines to use this specific path save for qball1, which Giri requested not be touched.

**Comment by MRphysics4life** [comment]
Fantastico! Danke schoen!
