### ISSUE TITLE
Gateway01 on KSPACE

### ISSUE THREAD

**Issue by MRphysics4life** [kmcgregor123456/CVNRimagingCore#4]
![screen shot 2018-04-04 at 10 44 48 am](https://user-images.githubusercontent.com/18470472/38315371-5942a628-37f6-11e8-88f9-bf66ef3cdf26.png)
Hi,
Gateway01 will not open on KSPACE Mac. The windows machine was restarted, so this seems to be an issue with KSPACE.
Best,
LCK

**Comment by kmcgregor123456** [comment]
Closed. The problem was that the version was RDC8. Install RDC 10 to fix. The issue is that the certificate isn't signed since we don't want to pay money to get certified certificates or create an authentication server.
