### ISSUE TITLE
3dttest++ on lens

### ISSUE THREAD

**Issue by GiriKrish** [kmcgregor123456/CVNRimagingCore#46]
Some of the  newer options (such as -Xclustsim) within 3dttest++ command does not run on lens. It gives the FATAL ERROR : 3dttest++: don't recognize option '-Xclustsim' (argv[31]). It runs on qball1 though. I think having homogeneity across all machines will be very helpful.

Thanks,
Giri.

**Comment by kmcgregor123456** [comment]
This has been updated. The local /usr/local/afni path overrode the /usr/lib/afni path on lens. I updated all of the machines by symlinking:

ln -s /usr/local/afni to /usr/lib/afni/bin
