### ISSUE TITLE
Tshift

### ISSUE THREAD

**Issue by awoodbu** [kmcgregor123456/CVNRimagingCore#47]
We are having issues running Tshift.  We have different issues depending on the computer used (lens vs. ralph vs. qb1).

On lens and qb1, Tshift will not run (per our earlier discussion).  On ralph, the script will run and create an appropriately titled Tshift file with what appears to be 350 volumes in Afni, but in Afni, opens up "empty image" and we cannot see anything.  

Here are the error messages we received when running the script:
slice time correction for MB rest fMRI data
extract raw slicetime pattern
extract final slicetime pattern
transpose final slicetime pattern
./Tshift_volreg_rsfcMRI_AW.sh: line 33: 3dTshift: command not found
finish slice time correction for MB task fMRI data
motion correction with reference of the middle volume of rest data 
./Tshift_volreg_rsfcMRI_AW.sh: line 37: 3dvolreg: command not found
finish motion correction

**Comment by kmcgregor123456** [comment]
this was the change in path for the symlinks...sorry
