### ISSUE TITLE
FSL not opening

### ISSUE THREAD

**Issue by awoodbu** [kmcgregor123456/CVNRimagingCore#48]
FSL will not open in ralph or lens.  

We tried FSL eyes (Anna, Corinne, Giri) to try to view the images that weren't loading in Afni, but it would not open.

**Comment by kmcgregor123456** [comment]
Working on it now. I am updating FSLeyes to the latest FSL release. FSL really doesn't support fslview anymore. The qt3 error that you are getting is a windowing error. It means that a menu item isn't available within the library (i.e.- the libraries have been updated and fslview doesn't know to where to look). It's an end of life problem with software.


================
Keith M. McGregor, PhD
VA RR&D Atlanta CVNR
Emory University, Department of Neurology
352.359.8084
www.varrd.emory.edu<http://www.varrd.emory.edu>

________________________________

**Comment by kmcgregor123456** [comment]
I have to reboot LENS

**Comment by kmcgregor123456** [comment]
This is a bigger problem. I installed fsleyes on lens, which should work, but fslview is still throwing the error.

FSLeyes is buggy when running over a direct SSH connection, but runs OK from X2go.

**Comment by kmcgregor123456** [comment]
sudo aptitude build-dep mesa
sudo aptitude install scons llvm-dev
apt-get source mesa
cd mesa
scons libgl-xlib
export LD_LIBRARY_PATH=`pwd`/build/linux-x86_64-debug/gallium/targets/libgl-xlib/:${LD_LIBRARY_PATH}
glxinfo | grep 'GLX version:'

**Comment by kmcgregor123456** [comment]
those are my notes

**Comment by kmcgregor123456** [comment]
This installation worked for fsleyes. it now runs on pano and lens.

Everyone needs to add the following line to their .bashrc files in their home directory:
export LD_LIBRARY_PATH=/usr/lib/mesa-10.1.3/build/linux-x86_64-debug/gallium/targets/libgl-xlib:${LD_LIBRARY_PATH}
