### ISSUE TITLE
Script alternately runs on lens and ralph...?

### ISSUE THREAD

**Issue by awoodbu** [kmcgregor123456/CVNRimagingCore#51]
Error message:
-------- freesurfer-Linux-centos6_x86_64-stable-pub-v5.3.0 --------
Setting up environment for FreeSurfer/FS-FAST (and FSL)
FREESURFER_HOME   /usr/local/freesurfer
FSFAST_HOME       /usr/local/freesurfer/fsfast
FSF_OUTPUT_FORMAT nii.gz
SUBJECTS_DIR      /usr/local/freesurfer/subjects
MNI_DIR           /usr/local/freesurfer/mni
FSL_DIR           /usr/share/fsl/5.0
awoodbury@ralph:~/Woodbury_CDA1/05.scripts$ ./11_rsfMRI_mask_ventricles_in_MNI.sh
run ventricle segmentation on subject PENFS01 post
/usr/share/fsl/5.0/bin/first_flirt: 1: /usr/share/fsl/5.0/bin/first_flirt: /usr/lib/fsl/5.0/bin/imtest: not found
/usr/share/fsl/5.0/bin/first_flirt: 89: [: =: unexpected operator
/usr/share/fsl/5.0/bin/first_flirt: 1: /usr/share/fsl/5.0/bin/first_flirt: /usr/lib/fsl/5.0/bin/remove_ext: not found
/usr/share/fsl/5.0/bin/first_flirt: 1: /usr/share/fsl/5.0/bin/first_flirt: /usr/lib/fsl/5.0/bin/remove_ext: not found
initial registration 1
/usr/share/fsl/5.0/bin/first_flirt: 123: /usr/share/fsl/5.0/bin/first_flirt: /usr/lib/fsl/5.0/bin/flirt: not found
Stage 2: use subcortical mask
/usr/share/fsl/5.0/bin/first_flirt: 127: /usr/share/fsl/5.0/bin/first_flirt: /usr/lib/fsl/5.0/bin/flirt: not found
/usr/share/fsl/5.0/bin/first_flirt: 128: /usr/share/fsl/5.0/bin/first_flirt: /usr/lib/fsl/5.0/bin/convert_xfm: not found
/usr/share/fsl/5.0/bin/first_flirt: 132: /usr/share/fsl/5.0/bin/first_flirt: /usr/lib/fsl/5.0/bin/flirt: not found
Alternate Stage 2: Use brain mask
/usr/share/fsl/5.0/bin/first_flirt: 137: /usr/share/fsl/5.0/bin/first_flirt: /usr/lib/fsl/5.0/bin/flirt: not found
/usr/share/fsl/5.0/bin/first_flirt: 139: /usr/share/fsl/5.0/bin/first_flirt: /usr/lib/fsl/5.0/bin/convert_xfm: not found
/usr/share/fsl/5.0/bin/first_flirt: 141: /usr/share/fsl/5.0/bin/first_flirt: /usr/lib/fsl/5.0/bin/flirt: not found
/bin/rm: cannot remove '_tmp_stage*': No such file or directory
run segmentation of L-vent PENFS01 post
/usr/share/fsl/5.0/bin/run_first: 1: /usr/share/fsl/5.0/bin/run_first: /usr/lib/fsl/5.0/bin/remove_ext: not found
/usr/share/fsl/5.0/bin/run_first: 1: /usr/share/fsl/5.0/bin/run_first: /usr/lib/fsl/5.0/bin/imtest: not found
/usr/share/fsl/5.0/bin/run_first: 140: [: =: unexpected operator
linear transformation matrix file not found
run segmentation of R-vent PENFS01 post
/usr/share/fsl/5.0/bin/run_first: 1: /usr/share/fsl/5.0/bin/run_first: /usr/lib/fsl/5.0/bin/remove_ext: not found
/usr/share/fsl/5.0/bin/run_first: 1: /usr/share/fsl/5.0/bin/run_first: /usr/lib/fsl/5.0/bin/imtest: not found
/usr/share/fsl/5.0/bin/run_first: 140: [: =: unexpected operator
linear transformation matrix file not found
combine the ventricles into one volume PENFS01 post
++ 3dcalc: AFNI version=Debian-18.0.05+git24-gb25b21054~dfsg.1-1~nd14.04+1 (Jan 23 2018) [64-bit]
++ Authored by: A cast of thousands
** ERROR (nifti_image_read): failed to find header file for 'PENFS01_MPRAGE_deoblq_axRPI_optiBET_brain_rmbias_toMNI-R_LatVent_first.nii.gz'
** FATAL ERROR: can't open dataset PENFS01_MPRAGE_deoblq_axRPI_optiBET_brain_rmbias_toMNI-R_LatVent_first.nii.gz
** Program compile date = Jan 23 2018
++ 3dAutomask: AFNI version=Debian-18.0.05+git24-gb25b21054~dfsg.1-1~nd14.04+1 (Jan 23 2018) [64-bit]
++ Authored by: Emperor Zhark
++ Loading dataset /data/qb/Atlanta/Woodbury_CDA1/06.Imaging_data/PENFS/PENFS01/post/preprocfiles/rsfMRI/PENFS01_rsfMRI_post_Tshift_volreg_applytopup_denoised_t

**Comment by kmcgregor123456** [comment]
oh. that's the .profile error. I will fix.


================
Keith M. McGregor, PhD
VA RR&D Atlanta CVNR
Emory University, Department of Neurology
352.359.8084
www.varrd.emory.edu<http://www.varrd.emory.edu>

________________________________
