### ISSUE TITLE
ralph 3dmaskave

### ISSUE THREAD

**Issue by MRphysics4life** [kmcgregor123456/CVNRimagingCore#53]
ralph is not able to 3dmaskave... maybe upgrade the OS sooner rather than later?

![3dmaskave_screenshot](https://user-images.githubusercontent.com/18470472/44632609-ac1ca580-a94b-11e8-85ec-d8b7e84726d5.png)

**Comment by kmcgregor123456** [comment]
Should be fixed now.

**Comment by MRphysics4life** [comment]
Perfect. Thanks
