### ISSUE TITLE
Non-urgent Matlab license notification

### ISSUE THREAD

**Issue by smtran** [kmcgregor123456/CVNRimagingCore#55]
Hi Keith,

Here is the notification in Matlab as of Aug 29th for your review at your convenience:
        Your MATLAB license will expire in 32 days.
	Please contact your system administrator or
	MathWorks to renew this license.

Thank you for handling all of our core issues! 

Best,
Stella

**Comment by kmcgregor123456** [comment]
Will update on all machines after Mathworks license is renewed at SOM
