### ISSUE TITLE
MATLAB license error on falx

### ISSUE THREAD

**Issue by GiriKrish** [kmcgregor123456/CVNRimagingCore#60]
Below is the error message on falx :

License checkout failed.
License Manager Error -10
Your license for Image_Toolbox has expired.
Expire date:  30-sep-2018
If you are not using a trial license contact your License Administrator to obtain an updated passcode.
Otherwise, contact your Sales Representative for a trial extension.

Troubleshoot this issue by visiting:
http://www.mathworks.com/support/lme/R2015b/10

Diagnostic Information:
Feature: Image_Toolbox
License path:
/net/giri/.matlab/R2015b_licenses:/usr/local/MATLAB/R2015b/licenses/license.dat:/usr/local/MATLAB/R2015b/licenses/license_falx_300274_R2015b.lic
Licensing error: -10,32.

**Comment by kmcgregor123456** [comment]
should be ok now
