### ISSUE TITLE
MATLAB not activated on genu

### ISSUE THREAD

**Issue by GiriKrish** [kmcgregor123456/CVNRimagingCore#61]
I have couple of intense (and heavy duty) MATLAB processing jobs (will take several days to finish)  that need to be finished ASAP for a paper, and I'm not able to run them from either falx (see the previous Issue #60), or genu. ASAP help is much appreciated.

Thanks,
Giri.

**Comment by GiriKrish** [comment]
I am now running a MATLAB script from ralph...fingers crossed! Let's not reboot ralph for next few days, please! Thanks. :-)

**Comment by kmcgregor123456** [comment]
ok
