### ISSUE TITLE
Software upgrades

### ISSUE THREAD

**Issue by kmcgregor123456** [kmcgregor123456/CVNRimagingCore#8]
Requests have been made to update our imaging hardware to a Puppet type system for systems management. This means replicating a single computer profile to all computer systems attached to the CVNR. This will take time to implement as puppet requires considerable implementation resources.

**Comment by kmcgregor123456** [comment]
We may want to switch to AWX Tower from Ansible. Investigating that option now.

Docker is another option, but I am not sure it is ideal.

**Comment by kmcgregor123456** [comment]
https://neurostars.org/t/using-docker-to-distribute-highres-neuroimaging-software/442

**Comment by MRphysics4life** [comment]
Docker sounds complicated and time consuming. If we can find a stable release of AWX, maybe that would work?

**Comment by kmcgregor123456** [comment]
Upgrades are proceeding incrementally.

Currently at 18.04:
ralph.birc.emory.edu
genu.birc.emory.edu
falx.birc.emory.edu
qball3.birc.emory.edu

Currently at 14.04:
lens.birc.emory.edu
pano.birc.emory.edu
qballs1,2,4

**Comment by kmcgregor123456** [comment]
qBall2 has been updated to Ubuntu 18.04
